name = "cf-worker-url-shortner"
compatibility_date = "2023-12-01"

[vars]
API_TOKEN = "l15xTy9IxjK3BO-mgEVefVvhk9FFNRgXEo4YBHPS"

[[d1_databases]]
binding = "D1_Database"
database_name = "url-shortner"
database_id = "14386217-85de-464f-9b34-edb83caff167"
